### RUTA INICIAL DE LA API
GET http://localhost:3000/api/


########################
#        AUTH          #
########################

### REGISTER - Crear usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Cesar",
  "email": "cesar@test.com",
  "phone": "98765432",
  "password": "12345678"
}

### LOGIN - Obtener token JWT
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "cesar@test.com",
  "password": "12345678"
}


########################
#    PUBLICACIONES     #
########################

# 👉 Después de hacer LOGIN, copia el token que te devuelve
# y pegalo en la variable @token de abajo

@token = Pega_aqui_el_token_del_login

### GET Obtener todas las publicaciones (PÚBLICO)
GET http://localhost:3000/api/publicaciones

### GET Obtener una publicación por ID (PÚBLICO)
@postID = a6093bc3-c29e-11f0-b0db-6e0506219b55
GET http://localhost:3000/api/publicaciones/{{postID}}

### POST Crear una nueva publicación (PROTEGIDO)
POST http://localhost:3000/api/publicaciones
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Publicación desde auth",
  "description": "Probando creación con token"
}

### PUT Actualizar una publicación por ID (PROTEGIDO)
PUT http://localhost:3000/api/publicaciones/{{postID}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Publicación Actualizada desde auth",
  "description": "Probando actualización con token"
}

### DELETE Eliminar una publicación por ID (PROTEGIDO)
DELETE http://localhost:3000/api/publicaciones/{{postID}}
Authorization: Bearer {{token}}
